// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI0vf32GMX__ZcRLW-sMUntw9jM6Em_Zc',
    appId: '1:486220515995:web:44cd59d9ec6bcde70a543e',
    messagingSenderId: '486220515995',
    projectId: 'tfg-salesianos',
    authDomain: 'tfg-salesianos.firebaseapp.com',
    storageBucket: 'tfg-salesianos.firebasestorage.app',
    measurementId: 'G-BS1RW64D1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpQEo6VhrZXRUgpm5y-zyz-d9ytMb7z4Q',
    appId: '1:486220515995:android:611f7e71f866b9830a543e',
    messagingSenderId: '486220515995',
    projectId: 'tfg-salesianos',
    storageBucket: 'tfg-salesianos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV5pEIFQAqncKMGvbTFhmp5a0JMYSDctk',
    appId: '1:486220515995:ios:6226d060f087146d0a543e',
    messagingSenderId: '486220515995',
    projectId: 'tfg-salesianos',
    storageBucket: 'tfg-salesianos.firebasestorage.app',
    iosBundleId: 'com.example.aplicacionMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV5pEIFQAqncKMGvbTFhmp5a0JMYSDctk',
    appId: '1:486220515995:ios:6226d060f087146d0a543e',
    messagingSenderId: '486220515995',
    projectId: 'tfg-salesianos',
    storageBucket: 'tfg-salesianos.firebasestorage.app',
    iosBundleId: 'com.example.aplicacionMovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI0vf32GMX__ZcRLW-sMUntw9jM6Em_Zc',
    appId: '1:486220515995:web:164059f32baeaf2c0a543e',
    messagingSenderId: '486220515995',
    projectId: 'tfg-salesianos',
    authDomain: 'tfg-salesianos.firebaseapp.com',
    storageBucket: 'tfg-salesianos.firebasestorage.app',
    measurementId: 'G-2GQ485Z8LF',
  );
}
